hydra:
  run:
    dir: .
  output_subdir: null
  job_logging: null
  hydra_logging: null

num_workers: 2
seed: 7
log_offline: false

# ===== Resuming =====
resume_checkpoint: null

# ===== Data =====
data_folder: ../data
dataset: java-med-10per1

max_labels: 9000
max_label_parts: 7
max_tokens: 45000
max_token_parts: 5

max_tree_nodes: 250
max_tree_depth: 20

# ===== Hyperparameters =====
hyper_parameters:
  n_epochs: 7
  patience: 10
  batch_size: 512
  clip_norm: 5

  optimizer: "RAdam"
  nesterov: true
  learning_rate: 0.01
  weight_decay: 0
  strategy: "decay"
  lr_decay_gamma: 0.95

# ===== Training parameters =====
initialization: "normal"
init_value: null
val_every_epoch: 1
save_every_epoch: 1
log_every_step: 10
progress_bar_refresh_rate: 1


# ===== Model parameters =====
teacher_forcing: 1
embedding_size: 128
encoder_dropout: 0.25
encoder_size: 128
decoder_size: 320
decoder_num_layers: 1
rnn_dropout: 0.5

