hydra:
  run:
    dir: .
  output_subdir: null
  job_logging: null
  hydra_logging: null

num_workers: 4
seed: 7
log_offline: false

# ===== Resuming =====
resume_checkpoint: null

# ===== Data =====
data_folder: ../data
dataset: java-small-asts

max_labels: 9000
max_label_parts: 7
max_tokens: 45000
max_token_parts: 5

max_tree_nodes: 250
max_tree_depth: 20

# ===== Hyperparameters =====
learning_rate: 0.01
weight_decay: 0
lr_decay_gamma: 0.95

batch_size: 512
n_epochs: 100

patience: 10
clip_norm: 5
teacher_forcing: 1

# ===== Training parameters =====
val_every_epoch: 1
save_every_epoch: 1
log_every_step: 10
progress_bar_refresh_rate: 1


# ===== Model parameters =====
embedding_size: 128
encoder_dropout: 0.25
encoder_size: 128
decoder_size: 320
decoder_num_layers: 1
rnn_dropout: 0.5
