experiment_setup:
  executable: code_transformer/experiments/code_transformer/code_summarization.py
data_setup:
  language: java-small
  use_validation: true
  num_sub_tokens: 5
  num_subtokens_output: 6
  use_only_ast: false
  mask_all_tokens: false
  use_no_punctuation: true
  use_pointer_network: true
  sort_by_length: false
  shuffle: false
  chunk_size: 32
data_transforms:
  max_distance_mask: None
  relative_distances:
  - ppr
  - ancestor_sp
  - sibling_sp
  - shortest_paths
  distance_binning:
    type: exponential
    growth_factor: 1.3
    n_fixed_bins: 9
transfer_learning:
  use_pretrained_model: true
  model_type: ct_code_summarization
  run_id: CT-20
  snapshot_iteration: 30000
  cpu: false
  freeze_encoder_layers: None
model:
  with_cuda: true
  label_smoothing: 0.1
  lm_encoder:
    input_nonlinearity: tanh
    num_languages: None
    transformer:
      num_layers: 3
      encoder_layer:
        d_model: 1024
        nhead: 8
        dim_feedforward: 2048
        dropout: 0.2
        activation: gelu
        use_content_content: true
        use_content_pos: true
        use_pos_content: true
        use_pos_pos: true
        use_token_distances: true
  lm_decoder:
    output_nonlinearity: None
    n_layers: 1
    decoder_dropout: 0
    decoder_nhead: 8
    decoder_dim_feedforward: 2048
    decoder_activation: gelu
    use_teacher_forcing: true
    pointer_attention_type: additive
    use_pointer_query_self_attention: false
    concat_query_and_pointer: true
    attend_cls_token: false
optimizer:
  optimizer: Adam
  learning_rate: 8.0e-05
  reg_scale: 3.0e-05
training:
  random_seed: 456
  batch_size: 8
  simulated_batch_size: 64
  simulated_batch_size_valid: 18
  accumulate_tokens_batch: false
  persistent_snapshot_every: 205
  early_stopping_patience: 10
  max_validation_samples: 50000
  metrics:
  - top1_accuracy
  - top5_accuracy
  - non_trivial_accuracy
  - precision
  - recall
  - f1_score
  - micro_f1_score
  - rouge_2
  - rouge_l
