hydra:
  run:
    dir: .
  output_subdir: null
  job_logging: null
  hydra_logging: null

num_workers: 4
seed: 7
log_offline: false

# ===== Resuming =====
resume_checkpoint: null

# ===== Data =====
data_folder: data  #/home/anton/CodeSearchNet/dataset/CodeXGLUE-source-code-asts
dataset: codexglue-docstrings-py
output_dir: data/outputs  # /home/anton/CodeSearchNet/dataset/CodeXGLUE-source-code-asts/outputs/gat-sgd

max_labels: 9000
max_label_parts: 15
max_tokens: 45000
max_node_token_parts: 5
max_ast_nodes: 250
max_source_parts: 100

# ===== Hyperparameters =====
hyper_parameters:
  n_epochs: 5
  patience: 10
  batch_size: 512
  clip_norm: 5
    
  optimizer: "Momentum"
  start_from: 0
  cycle_len: 6574
  min_lr: 0.001
  max_lr: 0.0074
  nesterov: true
  learning_rate: 0.01
  weight_decay: 0
  strategy: "decay"
  lr_decay_gamma: 0.95

# ===== Training parameters =====
initialization: null
init_value: null
val_every_epoch: 1
save_every_epoch: 1
log_every_step: 10
progress_bar_refresh_rate: 1


# ===== Model parameters =====
decoder_type: simple_decoder  # leclair_decoder
teacher_forcing: 1
embedding_size: 128
hidden_size: 256
encoder_num_layers: 1
decoder_num_layers: 1
rnn_dropout: 0.5

gnn_encoder:
  type: "gcn"
  n_heads: 1
  hidden_size: 128
  leaky_relu_negative_slope: 0.2
  dropout: 0.5
  use_bias: True
  norm: True
  residual: False
  rnn_cell: none  # gru / lstm
  normalization_layer: none  # layer_norm / batch_norm (TODO)
  num_hops: 5

